### ISSUE TITLE
サインアップ、サインイン機能実装

### ISSUE THREAD

**Issue by fumimi** [jun-marron/pham_bench#1]

**Comment by jun-marron** [comment]
・サインアップ前画面："医療関係者"yes or no
yes→sign up 画面へ
no→home画面に戻る

・サインアップ画面:name, emale, password,
・サインイン画面：emal,password

**Comment by jun-marron** [comment]
・サインアップ前画面：モーダルウインドウ追加？しました。
動作確認できていますが、少しコード書き換える予定です。

**Comment by fumimi** [comment]
@jun-marron 
マージ済み
