### ISSUE TITLE
#8サインイン、サインアップ失敗アラート作成

### ISSUE THREAD

**Issue by jun-marron** [jun-marron/pham_bench#8]
サインイン、サインアップ失敗時のエラーメッセージを表示します。

## 3. emailとパスワードの組み合わせが一致しない場合
・名前が入力されていません。
・emailが入力されていません。
・パスワードは8文字以上で設定してください。
・パスワードが一致しません。

**Comment by fumimi** [comment]
@jun-marron 
レビューしました。バリデーションエラーのパターンの洗い出しをお願いします。
